config/routes.rb
Rails.application.routes.draw do
  get 'messages/index', as: 'user_root'

  devise_for :users
  resources :comments

  resources :messages
  
  root 'messages#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_nested_set :scope => [:commentable_id, :commentable_type]

  validates :body, :presence => true
  validates :user, :presence => true

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_votable

  belongs_to :commentable, :polymorphic => true

  # NOTE: Comments belong to a user
  belongs_to :user

  # Helper class method that allows you to build a comment
  # by passing a commentable object, a user_id, and comment text
  # example in readme
  def self.build_from(obj, user_id, comment)
    new \
      :commentable => obj,
      :body        => comment,
      :user_id     => user_id
  end

  #helper method to check if a comment has children
  def has_children?
    self.children.any?
  end

  # Helper class method to lookup all comments assigned
  # to all commentable types for a given user.
  scope :find_comments_by_user, lambda { |user|
    where(:user_id => user.id).order('created_at DESC')
  }

  # Helper class method to look up all comments for
  # commentable class name and commentable id.
  scope :find_comments_for_commentable, lambda { |commentable_str, commentable_id|
    where(:commentable_type => commentable_str.to_s, :commentable_id => commentable_id).order('created_at DESC')
  }

  # Helper class method to look up a commentable object
  # given the commentable class name and id
  def self.find_commentable(commentable_str, commentable_id)
    commentable_str.constantize.find(commentable_id)
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
    acts_as_commentable
    validates :text_message, presence: true, length: { minimum: 4 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    def create
	commentable = commentable_type.constantize.find(commentable_id)
	@comment = Comment.build_from(commentable, current_user.id, body)
	
	respond_to do |format|
	    if @comment.save
		make_child_comment
		format.html { redirect_to(:back, :notice => 'Comment was successfully added.') }
	    else
		format.html { render :action => "new" }
	    end
	end
    end
    
    private
    
    def comment_params
	params.require(:comment).permit(:body, :commentable_id, :commentable_type, :comment_id)
    end
    
    def commentable_type
	comment_params[:commentable_type]
    end
    
    def commentable_id
	comment_params[:commentable_id]
    end
    
    def comment_id
	comment_params[:comment_id]
    end
    
    def body
	comment_params[:body]
    end
    
    def make_child_comment
	return "" if comment_id.blank?
	
	parent_comment = Comment.find comment_id
	@comment.move_to_child_of(parent_comment)
    end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    #@messages = Message.all
    @messages = Message.all.order(:date_message).reverse_order
    @message = Message.new
##    @messages.each do |message|
#	@new_comment = Comment.build_from(message, current_user.id, "")
#	@comment = Comment.build_from(message, current_user.id, "")
#    end
    #commentable = commentable_type.constantize.find(commentable_id)
    #@comment = Comment.build_from(commentable, current_user.id, body)
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @message = Message.find(params[:id])
    if user_signed_in?
        @new_comment = Comment.build_from(@message, current_user.id, "")
    end
    #@user_who_commented = current_chef
    #@comment = Comment.build_from( @message, @user_who_commented.id, "" )
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create

    @message = Message.new(message_params)

    time = Time.new
    @message.date_message = time.strftime("%Y-%m-%d %H:%M:%S")

    respond_to do |format|
      if @message.save
        #format.html { redirect_to @message, notice: 'Message was successfully created.' }
        #format.json { render :show, status: :created, location: @message }
        format.html { redirect_to '/messages', notice: 'Message was successfully created.' }
        format.json { render :index, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end



  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:date_message, :text_message)
    end
    
#    def comment_params
#	params.require(:comment).permit(:body, :commentable_id, :commentable_type, :comment_id)
#    end
#    
#    def commentable_type
#	comment_params[:commentable_type]
#    end
#    
#    def commentable_id
#	comment_params[:commentable_id]
#    end
#    
#    def comment_id
#	comment_params[:comment_id]
#    end
#    
#    def body
#	comment_params[:body]
#    end
#    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def profile
    if user_signed_in?
	redirect_to("/messages")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_form.html.erb
<%= form_for @new_comment do |f| %>
    <%= f.hidden_field :commentable_id, value: @new_comment.commentable_id %>
    <%= f.hidden_field :commentable_type, value: @new_comment.commentable_type %>
    <div class="field form-group">
	<%= f.text_area :body, class: 'form-control', rows: 5, cols: 100 %>
    </div>
    <div class="field form-group">
	<%= submit_tag "Messge comment", class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/comments/_reply.html.erb
<% comments.each do |comment| %>
    <div class="comments-show">
	<div class="comment">
	    <p><%= comment.body %><br></p>
	    <div class="comment-nav"><a href="#" class="comment-reply">Reply</a></div>
	    <div class="reply-form">
		<%= form_for @new_comment do |f| %>
		    <%= f.hidden_field :commentable_id, value: @new_comment.commentable_id %>
		    <%= f.hidden_field :commentable_type, value: @new_comment.commentable_type %>
		    <%= f.hidden_field :comment_id, value: comment.id %>
		    <div class="field form-group">
			<%= f.text_area :body, class: 'form-control', rows: 4, cols: 80 %>
		    </div>
		    <div class="field form-group">
			<%= submit_tag "Post Reply", class: 'btn btn-primary' %>
		    </div>
		<% end %>
	    </div>
	</div>
	<%= render partial: "comments/reply", locals: {comments: comment.children} %>
    </div>
<% end %>

app/views/comments/_template.html.erb
<%= render partial: "comments/form", locals: {new_comment: new_comment} %>

<div class="commets-container">
    <%= render partial: "comments/reply", locals: {comments: commentable.root_comments} %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Messages</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>
<p id="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!--<div class="field">
    <%= f.label :date_message %><br>
    <%= f.text_field :date_message %>
  </div>-->
  <div class="field">
    <%= f.label :text_message %><br>
    <%= f.text_area :text_message, rows: 5, cols: 100 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<!--<h1>Listing messages</h1>-->

<% if user_signed_in? %>
    
    <div class="main-message">
        <p>Hello, <%= current_user.email %></p>
	<p>You can create a New Message</p>
	<%= render 'form' %>
	<p>or <%= link_to 'Exit', destroy_user_session_path, :method => :delete %></p>
    </div>
<% else %>
    <div class="main-message">
	<p>You must <%= link_to 'Enter', new_user_session_path %> or <%= link_to 'Register', new_user_registration_path %> to leave a message</p>
    </div>
<% end %>


    <% @messages.each do |message| %>
      <div class="<%= cycle('message_line_odd', 'message_line_even') %>"><p>
        <span><%= message.date_message %></span>
        <span><%= message.text_message %></span>
        <span class="message_actions">
        <% if user_signed_in? %>
    	    <%= link_to 'Show', message %>
    	    <%= link_to 'Edit', edit_message_path(message) %>
    	    <%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %>
    	<% end %>
    	</span></p>
      </div>
    <% end %>

<br>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<!--<p id="notice"><%= notice %></p>-->

<div class="show-message">
	<p>
	    <span><%= @message.date_message %></td>
	    <span><%= @message.text_message %></td>
	</p>
</div>

<% if user_signed_in? %>
    <%= render partial: "comments/template", locals: {commentable: @message, new_comment: @comment} %>
<% end %>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/welcome/profile.html.erb
<% if user_signed_in? %>
    <p>Hello, <%= current_user.email %></p>
    <%= link_to 'Exit', destroy_user_session_path, :method => :delete %>
<% else %>
    You must <%= link_to 'Enter', new_user_session_path %> or <%= link_to 'Register', new_user_registration_path %> to leave a message
<% end %>